{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"provenance":[],"authorship_tag":"ABX9TyN3JBQmw7s540RKK4lewE41"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"}},"cells":[{"cell_type":"code","execution_count":1,"metadata":{"id":"0g9rKFmvVStx","executionInfo":{"status":"ok","timestamp":1724250933792,"user_tz":300,"elapsed":364,"user":{"displayName":"Abraham Zamudio","userId":"17856795790189684981"}}},"outputs":[],"source":["# Para crear/definir/implementar nuestra propia excepcion debemos considerar que la clase Exception\n","# sea la clase padre de nuestra propia excepcion\n","\n","# Definir una subclase : MiExcepcionPersonalizada\n","# Clase Padre : Exception\n","\n","class MiExcepcionPersonalizada(Exception):\n","  pass"]},{"cell_type":"code","source":["# Lancemos/ejecutemos/instanciemos mi subclase personalizada\n","raise MiExcepcionPersonalizada()"],"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":158},"id":"Z5u6QYzVXTZi","executionInfo":{"status":"error","timestamp":1724251003082,"user_tz":300,"elapsed":340,"user":{"displayName":"Abraham Zamudio","userId":"17856795790189684981"}},"outputId":"411b1ece-1a55-44c8-de05-cfc2717e200c"},"execution_count":2,"outputs":[{"output_type":"error","ename":"MiExcepcionPersonalizada","evalue":"","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mMiExcepcionPersonalizada\u001b[0m                  Traceback (most recent call last)","\u001b[0;32m<ipython-input-2-39146ef74eee>\u001b[0m in \u001b[0;36m<cell line: 2>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0;31m# Lancemos/ejecutemos/instanciemos mi subclase personalizada\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 2\u001b[0;31m \u001b[0;32mraise\u001b[0m \u001b[0mMiExcepcionPersonalizada\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;31mMiExcepcionPersonalizada\u001b[0m: "]}]},{"cell_type":"code","source":["# Documentacion MiExcepcionPersonalizada\n","help(MiExcepcionPersonalizada)"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"collapsed":true,"id":"ePAm_WbyXuoc","executionInfo":{"status":"ok","timestamp":1724251065810,"user_tz":300,"elapsed":338,"user":{"displayName":"Abraham Zamudio","userId":"17856795790189684981"}},"outputId":"921feace-cb76-418c-c0f1-7f98a83a253f"},"execution_count":3,"outputs":[{"output_type":"stream","name":"stdout","text":["Help on class MiExcepcionPersonalizada in module __main__:\n","\n","class MiExcepcionPersonalizada(builtins.Exception)\n"," |  Method resolution order:\n"," |      MiExcepcionPersonalizada\n"," |      builtins.Exception\n"," |      builtins.BaseException\n"," |      builtins.object\n"," |  \n"," |  Data descriptors defined here:\n"," |  \n"," |  __weakref__\n"," |      list of weak references to the object (if defined)\n"," |  \n"," |  ----------------------------------------------------------------------\n"," |  Methods inherited from builtins.Exception:\n"," |  \n"," |  __init__(self, /, *args, **kwargs)\n"," |      Initialize self.  See help(type(self)) for accurate signature.\n"," |  \n"," |  ----------------------------------------------------------------------\n"," |  Static methods inherited from builtins.Exception:\n"," |  \n"," |  __new__(*args, **kwargs) from builtins.type\n"," |      Create and return a new object.  See help(type) for accurate signature.\n"," |  \n"," |  ----------------------------------------------------------------------\n"," |  Methods inherited from builtins.BaseException:\n"," |  \n"," |  __delattr__(self, name, /)\n"," |      Implement delattr(self, name).\n"," |  \n"," |  __getattribute__(self, name, /)\n"," |      Return getattr(self, name).\n"," |  \n"," |  __reduce__(...)\n"," |      Helper for pickle.\n"," |  \n"," |  __repr__(self, /)\n"," |      Return repr(self).\n"," |  \n"," |  __setattr__(self, name, value, /)\n"," |      Implement setattr(self, name, value).\n"," |  \n"," |  __setstate__(...)\n"," |  \n"," |  __str__(self, /)\n"," |      Return str(self).\n"," |  \n"," |  with_traceback(...)\n"," |      Exception.with_traceback(tb) --\n"," |      set self.__traceback__ to tb and return self.\n"," |  \n"," |  ----------------------------------------------------------------------\n"," |  Data descriptors inherited from builtins.BaseException:\n"," |  \n"," |  __cause__\n"," |      exception cause\n"," |  \n"," |  __context__\n"," |      exception context\n"," |  \n"," |  __dict__\n"," |  \n"," |  __suppress_context__\n"," |  \n"," |  __traceback__\n"," |  \n"," |  args\n","\n"]}]},{"cell_type":"code","source":["# Lista de metodos que se puede aplicar a un objeto que es instancia de la clase MiExcepcionPerdonalizada\n","x1 = MiExcepcionPersonalizada()\n","dir(x1)"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"19TDYZPlY6GW","executionInfo":{"status":"ok","timestamp":1724251422666,"user_tz":300,"elapsed":374,"user":{"displayName":"Abraham Zamudio","userId":"17856795790189684981"}},"outputId":"7eb6b88b-0a14-4fcb-da90-e21b0c090048"},"execution_count":6,"outputs":[{"output_type":"execute_result","data":{"text/plain":["['__cause__',\n"," '__class__',\n"," '__context__',\n"," '__delattr__',\n"," '__dict__',\n"," '__dir__',\n"," '__doc__',\n"," '__eq__',\n"," '__format__',\n"," '__ge__',\n"," '__getattribute__',\n"," '__gt__',\n"," '__hash__',\n"," '__init__',\n"," '__init_subclass__',\n"," '__le__',\n"," '__lt__',\n"," '__module__',\n"," '__ne__',\n"," '__new__',\n"," '__reduce__',\n"," '__reduce_ex__',\n"," '__repr__',\n"," '__setattr__',\n"," '__setstate__',\n"," '__sizeof__',\n"," '__str__',\n"," '__subclasshook__',\n"," '__suppress_context__',\n"," '__traceback__',\n"," '__weakref__',\n"," 'args',\n"," 'with_traceback']"]},"metadata":{},"execution_count":6}]},{"cell_type":"code","source":["# Tambien podemos pasar argumentos de entrada al lanzar nuestra subclase\n","# Ejemplo : Pasemos dos argumentos al lanzar nuestra excepcion . Para ello necesitamos\n","# modificar la funcion __init__() de la siguiente manera\n","\n","# MOdifiquemos el metodo __init__ de nuestra excepcion personalizada\n","class MiExcepcionPersonalizada(Exception):\n","  def __init__(self, parametro1, parametro2):\n","    self.parametro1 = parametro1\n","    self.parametro2 = parametro2"],"metadata":{"id":"wHw_iFWSYHmx","executionInfo":{"status":"ok","timestamp":1724251673723,"user_tz":300,"elapsed":331,"user":{"displayName":"Abraham Zamudio","userId":"17856795790189684981"}}},"execution_count":7,"outputs":[]},{"cell_type":"code","source":["#\n","x2 = MiExcepcionPersonalizada(\"Python\", \"Intermedio\")"],"metadata":{"id":"EFuCnneWaJmG","executionInfo":{"status":"ok","timestamp":1724251704200,"user_tz":300,"elapsed":335,"user":{"displayName":"Abraham Zamudio","userId":"17856795790189684981"}}},"execution_count":8,"outputs":[]}]}